### PR TITLE
Add support for OS/2 BeginLibPath directive.

### PR DESCRIPTION
**Pull request by StevenLevine**
Resolves ticket #758.

### CODE REVIEW

**Comment by StevenLevine** [comment]
I should probably test the build for this pull request before the world gets to see it.

**Comment by psmedley** [comment]
https://smedley.id.au/tmp/httpd-2.4.53-os2-debug-20220528.zip will be up shortly and will contain this PR.

**Comment by StevenLevine** [comment]
This seems to work as intended using:

  BeginLibPath "d:/Internet/php7;d:/Internet/php8"

This allows me to switch between php7 and php8 with a single httpd.conf edit.
I'm working towards a no-edit switching solution but it's not finished yet.

>set BEGINLIBPATH
Not in environment "BEGINLIBPATH"

>httpd -d..
Apache/2.4.53 (OS/2) PHP/7.4.28

Without the directive, we get the expected:

>httpd -d..
httpd.exe: Syntax error on line 185 of ../conf/httpd.conf: Cannot load modules/modphp7.dll into server: SYS0002: The system cannot find the file specified.  (PHP7)

I think we can safely let this build go public.

What do you think about the idea of committng readme.os2 to the repo, so we can keep it updated with a list of new features?

**Comment by psmedley** [comment]
Agree, adding readme.os2 is  a good  thought. Automatically updating it  with a git  log would be good too :)

**Pull request merged**
